### ISSUE TITLE
Not able to compile .rmf

### ISSUE THREAD

**Issue by Dmx6** [cmbasnett/dod_kaust#1]
Hello,
i was trying to compile the .rmf but am getting an error:

Error: Entity 1184 has no visible brushes

Error: No visibile brushes
Description: All brushes are CLIP or ORIGIN (at least one must be normal/visible)
Howto Fix: self explanitory

Are there any special settings i have to give the ZHLT Build Programs?

**Comment by cmbasnett** [comment]
The compile settings can be found [here](https://github.com/cmbasnett/dod_kaust#build-settings).

How are you trying to compile this? If you want you can add me on Discord (`colin.basnett`).

**Comment by Dmx6** [comment]
Ahh silly me was triying to compile it with the old Zoners ZHLT. I wasnt using Vluzacn tools to compile. Now the compile works. Thanks for sharing the map and making it open source. I am rusty, havent used the GoldSrc Hammer since 20 years or so :)

**Comment by cmbasnett** [comment]
No problem, glad it worked out! If you have any other questions feel free to add me on Discord.

**Comment by Dmx6** [comment]
Sadly Discord says you dont accept friend requests ;)
